bundle_conditions.resourceType=Bundle
bundle_conditions.narrative=classpath:ips/condition-narrative-template.html
bundle_conditions.profile=conditions

bundle_allergy_intolerance.resourceType=Bundle
bundle_allergy_intolerance.narrative=classpath:ips/allergies-narrative-template.html
bundle_allergy_intolerance.profile=allergies

bundle_medical_devices.resourceType=Bundle
bundle_medical_devices.narrative=classpath:ips/medical-devices-narrative-template.html
bundle_medical_devices.profile=medicalDevices

bundle_procedures.resourceType=Bundle
bundle_procedures.narrative=classpath:ips/procedures-narrative-template.html
bundle_procedures.profile=procedures